### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by addepalli8** [ConduitMobileRND/react-native-scratch#13]
@avinashlng1080 @comord @amitcomo @sutefan1 

tried this`https://github.com/ConduitMobileRND/react-native-scratch/issues/5#issuecomment-531897907` still not working 
unable to solve this issue for past couple of days
can u pls help me in here ?

<img width="760" alt="Screenshot 2020-10-15 at 1 53 14 PM" src="https://user-images.githubusercontent.com/42747069/96096728-c7611b00-0eed-11eb-9cf0-87e99ff3f4e1.png">
<img width="273" alt="Screenshot 2020-10-15 at 1 53 37 PM" src="https://user-images.githubusercontent.com/42747069/96096787-d47e0a00-0eed-11eb-9570-36a56cb794c2.png">

**Comment by sutefan1** [comment]
Hey @addepalli8 ,

as this module isn't prepared for +0.60 RN auto-linking (the podspec is missing for example) it needs some addition steps to finish the linking. 

There is an open PR which solves the issue, but this needs to be approved and merged. 

As long as this isn't happening, try this temporary solution:

1. Unlink RN-Scratch by removing all parts from your xcode project and the pods
2. Remove the node_module 
3. Remove it from the package json
4. insert this link instead in the dependencies brackets: 
```"react-native-scratch": "git+https://github.com/yannou788/react-native-scratch.git",```
5. run ```npm install``` and then ```cd ios && pod install```
6. Clean your xcode workspace/project and build it
7. Run ```npm run ios``` and it should work (make sure you've terminated the packager before)

**NOTE**: This is a temporary solution as mentioned above. If the PR is merged, please change back to the official module. Additionally, if @yannou788 is changing anything in the PR or his fork, the module might be broken. 

Hope this helps,
sutefan1

**Comment by jonathanroze** [comment]
Thank you @sutefan1 it's work well ! 

Do you know how to make the "erase" rounded instead of square ? Thank :)

**Comment by sutefan1** [comment]
@jonathanroze 
Glad I could help you out!
> Do you know how to make the "erase" rounded instead of square ? Thank :)

I haven't looked into yet, but maybe this PR (https://github.com/ConduitMobileRND/react-native-scratch/pull/10) is helping you out, at least on android!
